### ISSUE TITLE
[1.18.2Bug] Game Crash on the startup

### ISSUE THREAD

**Issue by OcrSu** [iglee42/CreateCasing#11]
ModVersion:1.18.2-1.1.2

1. Run The Game
2. Game Crashes
3. 
[crash-2023-04-21_13.43.27-fml.txt](https://github.com/iglee42/CreateCasing/files/11292719/crash-2023-04-21_13.43.27-fml.txt)

Java17
Win10
Ryzen7 5700x + RX6600

**Comment by iglee42** [comment]
Do you have create extended cogwheels ?

**Comment by OcrSu** [comment]
I'm not really sure what create extended cogwheels is, maybe it's a mod.
Here is my list of mods for create
![FJSVVB@QLR)CT FP}X`Z}_6](https://user-images.githubusercontent.com/75876201/233810912-7db852bb-365f-40af-bf8c-4be4c991bc62.png)


> Do you have create extended cogwheels ?

**Comment by PieKing1215** [comment]
> Do you have create extended cogwheels ?

Based on the log, looks like they don't have extended cogs so as a result the mixins from this mod are failing due to the class not existing.
If you want the extended cogs mixins to only run when extended cogs is present you can use a custom `IMixinConfigPlugin` to conditionally disable the mixins if it's not present.

Example of how to do it from one of my mods (pretty sure it should work basically the same on forge/fabric):
plugin class: https://github.com/PieKing1215/DripSounds-Fabric/blob/903ff758db10bca2a28a5f5d3083d65a0c7f805a/src/main/java/me/pieking1215/waterdripsound/mixin/DripSoundPlugin.java
(in shouldApplyMixin instead of returning true/false in the ifs you would do like `ModList.get().isLoaded("whateverthemodidis")`)

add "plugin" field to mixins.json: https://github.com/PieKing1215/DripSounds-Fabric/blob/903ff758db10bca2a28a5f5d3083d65a0c7f805a/src/main/resources/waterdripsound.mixins.json#L6

**Comment by iglee42** [comment]
This bug was fix in the next update

**Comment by OcrSu** [comment]
> This bug was fix in the next update

Game Crash on the startup too.....
[debug.log](https://github.com/iglee42/CreateCasing/files/11549811/debug.log)

in debug log 5168 line.
Mixin apply failed createcasing.mixins.json:minecraft.BlockEntityTypeMixin...........

ModVersion：
![XKZ(%P PT 7G1L$1ZFH1I0J](https://github.com/iglee42/CreateCasing/assets/75876201/20932d45-e876-4b9e-9fc1-c4ff7e069511)
CreateCasing-1.18.2-1.2.jar
